// This Code Autometically Generated by Twahanur Rahman. NOTE: Do not try to copy code, learn yourself
#include <bits/stdc++.h>
using namespace std;
int main()
{
    int s, d;
    cin >> s >> d;
    cout << s + d << endl;
    return 0;
}


// 4+9   13
// 4+6   10