// This Code Autometically Generated by Twahanur Rahman. NOTE: Do not try to copy code, learn yourself
#include <bits/stdc++.h>
using namespace std;
int main()
{
    long long int n;
    cin >> n;
    if (n > 2)
        cout << 25;
    else
        cout << pow(5, n);
    return 0;
}