// This Code Autometically Generated by Twahanur Rahman. NOTE: Do not try to copy code, learn yourself
#include <bits/stdc++.h>
using namespace std;
int main()
{
    string g, h, c;
    cin >> g >> h >> c; // input the strings "g","h" and "c
    string temp = g + h;
    sort(temp.begin(), temp.end());
    sort(c.begin(), c.end());
    if (temp == c)
        cout << "YES\n";
    else
        cout << "NO\n";
    return 0;
}