// This Code Autometically Generated by Twahanur Rahman. NOTE: Do not try to copy code, learn yourself
#include <bits/stdc++.h>
using namespace std;
int main()
{
    string s;
    int x = 0, t;
    cin >> t;
    while (t--)
    {
        cin >> s;

        if (s[1] == '+')
        {
            x++;
        }
        else if (s[1] == '-')
        {
            --x;
        }
    }
    cout << x << endl;
    return 0;
}