// This Code Autometically Generated by Twahanur Rahman. NOTE: Do not try to copy code, learn yourself
#include <bits/stdc++.h>
using namespace std;
int main()
{
    int t, x, count = 0;
    cin >> t;
    while (t--)
    {
        cin >> x;
        for (int i = 1; i <= 9; i++)
        {
            int a = i;
            for (int j = 1; j <= 4; j++)
            {
                if (a != x)
                {
                    a = i * pow(10, j) + a;
                    count = count + j;
                }
                else
                {
                    count = count + j;
                    break;
                }
            }
            if (a == x)
                break;
        }
        cout << count << endl;
        count = 0;
    }
    return 0;
}
// 1 11 111 1111