// This Code Autometically Generated by Twahanur Rahman. NOTE: Do not try to copy code, learn yourself
#include <bits/stdc++.h>
using namespace std;
bool isPrime(int n)
{
    for (int i = 2; i <= sqrt(n); i++) // Complexity O(SquareRoot(n))
    {
        if (n % i == 0)
            return false;
    }
    return true;
}

int main()
{
    int n;
    cin >> n;
    if (n > 11)
    {
        int x, y;
        if (n % 2 == 0)
        {
            x = (n / 2);
            y = x;
            while ((isPrime(x)) || (isPrime(y)))
            {
                if (isPrime(x) || isPrime(y))
                {
                    x++;
                    y--;
                }
                if (isPrime(x) && isPrime(y))
                    break;
            }
        }
        else
        {
            x = (n + 1) / 2;
            y = (n - 1) / 2;
            // 12 11
            while ((isPrime(x)) || (isPrime(y)))
            {
                if (isPrime(x) || isPrime(y))
                {
                    x++;
                    y--;
                }
                if (isPrime(x) && isPrime(y))
                    break;
            }
        }
        cout << x << " " << y << endl;
    }
    return 0;
}