// This Code Autometically Generated by Twahanur Rahman. NOTE: Do not try to copy code, learn yourself
#include <bits/stdc++.h>
using namespace std;
int main()
{
    int t;
    cin >> t;
    while (t--)
    {
        int x;
        cin >> x;
        if (x % 4 != 0)
        {
            cout << "NO" << endl;
        }
        else
            cout << "YES\n";
    }

    return 0;
}