// This Code Autometically Generated by Twahanur Rahman. NOTE: Do not try to copy code, learn yourself
#include <bits/stdc++.h>
using namespace std;
int main()
{
    int t, count = 0, min,max;
    cin >> t;
    int sc[t];
    for (int i = 0; i < t; i++)
    {
        cin >> sc[i];
    }
    min = sc[0];
    max=sc[0];
    for (int i = 1; i < t; i++)
    {
        if(sc[i]<min)
        {
            min=sc[i];
            count++;
        }else if(sc[i]>max){
            max=sc[i];
            count++;
        }
    }
    cout << count << endl;

    return 0;
}