// This Code Autometically Generated by Twahanur Rahman. NOTE: Do not try to copy code, learn yourself
#include <bits/stdc++.h>
using namespace std;
int main()
{
    int a;
    cin >> a;
    if (a & (a - 1))
        cout << "yes";
    else
        cout << "NO";
    return 0;
}