// This Code Autometically Generated by Twahanur Rahman. NOTE: Do not try to copy code, learn yourself
#include <bits/stdc++.h>
using namespace std;
int main()
{
    int student, item, puzzel[10001];

    cin >> student >> item;

    for (int i = 0; i < item; i++)
    {
        cin >> puzzel[i];
    }

    sort(puzzel, puzzel + item);

    int min = puzzel[item - 1] - puzzel[0];

    for (int i = 0; i < item - student + 1; i++)
    {
        if (puzzel[i + student - 1] - puzzel[i] < min)
        {
            min = puzzel[i + student - 1] - puzzel[i];
        }
    }
    cout << min << endl;

    return 0;
}