// This Code Autometically Generated by Twahanur Rahman. NOTE: Do not try to copy code, learn yourself
#include <bits/stdc++.h>
using namespace std;

void solve()
{
    int n;
    float k;
    int count = 0;
    cin >> n >> k;
    vector<int> arr(n, 0);
    // int arr[n];
    for (int i = 1; i < n + 1; ++i)
    {
        float x = ceil((float)i / k);
        cout << "x: " << x << " i: " << i << endl;
        if (x > count)
        {
            arr[i] = 1;
            count++;
        }
    }
    for (int v : arr)
        cout << v << " ";
    cout << endl;
    reverse(arr.begin(), arr.end());

    for (int i = 1; i < n + 1; i++)
    {
        float x = ceil((float)i / k);
        if (x > count)
        {
            count++;
        }
        if (arr[i] == 1)
            count++;
    }
    for (int v : arr)
        cout << v << " ";
    cout << endl;
    int result = 0;
    for (int i = 1; i < n + 1; i++)
    {
        if (arr[i] == 1)
            result++;
    }
    cout << result << endl;
}
int main()
{
    int t;
    cin >> t;
    while (t--)
    {
        solve();
        cout << "\n\n\n";
    }
    return 0;
}