// This Code Autometically Generated by Twahanur Rahman. NOTE: Do not try to copy code, learn yourself
#include <bits/stdc++.h>
using namespace std;
void solve()
{
    string s;
    cin >> s;
    if (s.size() % 2)
    {
        s.erase(s.begin() + s.size() / 2);
    }
    if (s != string(s.size(), s[0]))

    {
        cout << "YES" << endl;
    }
    else
    {
        cout << "NO" << endl;
    }
}
int main()
{
    int t;
    cin >> t;
    while (t--)
    {
        solve();
    }
    return 0;
}